const $=s=>document.querySelector(s),app=$('#app'),TOKEN='sb_token',PREF='sb_prefs';
const st={me:null,groups:[],group:null,tab:'inicio',theme:0,model:0};
const themes=[['Roxo Imperial','#241632','#34204b','#ff4fa3','#ffd166'],['Noite Rosa','#17121f','#302038','#ff4f9f','#f7c65c'],['Ameixa Dourada','#281527','#40203d','#f08ad1','#f3c969'],['Roxo Azul','#171a30','#27284d','#9d7cff','#ffd166'],['Violeta','#21182d','#382548','#d982ff','#f5c76b'],['Retrô','#f5edf8','#fff','#8e44ad','#d39b2a']];
const models=['Clássico','Perfil','Mural','Comunidades','Compacto','Livre'];
try{Object.assign(st,JSON.parse(localStorage.getItem(PREF)||'{}'))}catch{}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const save=()=>localStorage.setItem(PREF,JSON.stringify({theme:st.theme,model:st.model}));
function api(p,b,m){return fetch('/api/'+p,{method:m||(b?'POST':'GET'),headers:{'content-type':'application/json',...(localStorage[TOKEN]?{authorization:'Bearer '+localStorage[TOKEN]}:{})},body:b?JSON.stringify(b):undefined}).then(async r=>{let d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.erro||('HTTP '+r.status));return d})}
function av(n,c){let i=String(n||'?').split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase();return '<span class="avatar '+(c||'')+'">'+esc(i)+'</span>'}
function theme(){let t=themes[st.theme];document.documentElement.style.setProperty('--bg',t[1]);document.documentElement.style.setProperty('--card',t[2]);document.documentElement.style.setProperty('--pink',t[3]);document.documentElement.style.setProperty('--gold',t[4]);}
function toast(x){let t=$('#toast');if(!t){t=document.createElement('div');t.id='toast';document.body.append(t)}t.textContent=x;t.hidden=false;setTimeout(()=>t.hidden=true,4000)}
function shell(x){theme();app.innerHTML='<header class="top"><div class="brand"><img src="logo-icone.png"><span>SoCial<i>Br</i></span></div><div class="top-user">'+(st.me?av(st.me.nome):'')+'</div></header>'+x+'<div id="toast" hidden></div>'}
function login(){shell('<main class="landing"><section class="hero-card"><img src="logo-grande.png" class="hero-logo"><span class="eyebrow">SUA REDE. SEU ESPAÇO.</span><h1>O seu ambiente social, do seu jeito.</h1><p>Um painel inspirado nas redes clássicas, com espaço para você montar sua própria experiência.</p><form id="login"><input id="nome" maxlength="40" required placeholder="Como você quer ser chamado?"><button class="primary">Entrar no SoCialBr</button></form><small>Sem senha. Este aparelho guarda seu acesso.</small></section></main>');$('#login').onsubmit=async e=>{e.preventDefault();try{let r=await api('registrar',{nome:$('#nome').value.trim()});localStorage[TOKEN]=r.token;await boot()}catch(x){toast(x.message)}}}
async function boot(){try{st.me=await api('eu');st.groups=await api('grupos');let q=new URLSearchParams(location.search).get('convite');if(q){let r=await api('convites/aceitar',{token:q});history.replaceState(null,'',location.pathname);st.groups=await api('grupos');return loadGroup(r.group_id)}if(!st.groups.length){render();return}await loadGroup(st.groups[0].id)}catch(x){console.error('SoCialBr/D1:',x);shell('<main class="landing"><section class="hero-card error-card"><span class="eyebrow">ERRO DE CONEXÃO</span><h1>O SoCialBr não conseguiu acessar o banco.</h1><p class="error-detail">'+esc(x.message||'Erro desconhecido')+'</p><p>O erro acima é o retorno real da API. Nenhuma tabela ou cron foi alterado.</p><button class="primary" onclick="location.reload()">Tentar novamente</button><button class="ghost" onclick="localStorage.removeItem(TOKEN);location.reload()">Trocar acesso</button></section></main>')}}
async function loadGroup(id){try{st.group=await api('grupos/'+id+'/posts');render()}catch(x){toast(x.message)}}
function nav(){return '<nav class="nav">'+[['inicio','Início'],['perfil','Meu perfil'],['amigos','Amigos'],['comunidades','Comunidades'],['config','Personalizar']].map(x=>'<button class="'+(st.tab==x[0]?'active':'')+'" data-tab="'+x[0]+'">'+x[1]+'</button>').join('')+'</nav>'}
function render(){if(!st.me)return login();let x=st.tab==='config'?settings():st.tab==='perfil'?profile():st.tab==='amigos'?friends():st.tab==='comunidades'?communities():home();shell(nav()+'<main class="layout">'+x+'</main>');document.querySelectorAll('[data-tab]').forEach(x=>x.onclick=()=>{st.tab=x.dataset.tab;render()});let p=$('#post');if(p)p.onsubmit=async e=>{e.preventDefault();try{await api('grupos/'+st.group.grupo.id+'/posts',{texto:$('#texto').value.trim()});await loadGroup(st.group.grupo.id);toast('Publicado.')}catch(x){toast(x.message)}};let g=$('#groups');if(g)g.onchange=()=>loadGroup(g.value);document.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{st.theme=+b.dataset.theme;save();render()});document.querySelectorAll('[data-model]').forEach(b=>b.onclick=()=>{st.model=+b.dataset.model;save();render()});let ng=$('#newgroup');if(ng)ng.onsubmit=async e=>{e.preventDefault();try{let r=await api('grupos',{nome:$('#gname').value.trim()});st.groups=await api('grupos');await loadGroup(r.id)}catch(x){toast(x.message)}};let iv=$('#invite');if(iv)iv.onclick=invite}
function groupbar(){return '<div class="groupbar"><div><small>AMBIENTE ATUAL</small><strong>'+esc(st.group.grupo.nome)+'</strong></div><select id="groups">'+st.groups.map(g=>'<option value="'+g.id+'" '+(g.id===st.group.grupo.id?'selected':'')+'>'+esc(g.nome)+'</option>').join('')+'</select></div>'}
function home(){if(!st.group)return '<section class="welcome-panel"><span class="eyebrow">PRIMEIRO PASSO</span><h1>Crie seu primeiro ambiente.</h1><p>Comece com um grupo e depois personalize o painel.</p><form id="newgroup" class="inline-form"><input id="gname" required maxlength="50" placeholder="Nome do grupo"><button class="primary">Criar grupo</button></form></section>';let d=st.group,ms=d.membros||[],ps=d.posts||[];return groupbar()+'<section class="columns"><aside class="side"><div class="card profile-mini">'+av(st.me.nome,'large')+'<h2>'+esc(st.me.nome)+'</h2><p>Seu espaço no SoCialBr</p><button class="ghost" data-tab="perfil">Ver perfil</button></div><div class="card menu-card"><b>Atalhos</b><button data-tab="amigos">Amigos <span>'+ms.length+'</span></button><button data-tab="comunidades">Comunidades</button><button data-tab="config">Personalizar</button></div></aside><section class="feed"><div class="welcome-strip"><div><span>RECADO DO AMBIENTE</span><h2>O que está acontecendo?</h2></div><b class="spark">✦</b></div><form id="post" class="card composer"><textarea id="texto" maxlength="2000" placeholder="Escreva um recado para o grupo..."></textarea><div><small>Seu painel, suas regras.</small><button class="primary">Publicar</button></div></form>'+(ps.length?ps.map(p=>'<article class="card post"><div class="post-head">'+av(p.nome)+'<div><b>'+esc(p.nome)+'</b><small>'+new Date(p.criado_em).toLocaleString('pt-BR')+'</small></div></div><p>'+esc(p.texto)+'</p></article>').join(''):'<div class="empty card"><strong>O mural está esperando.</strong><span>Seja o primeiro a deixar um recado.</span></div>')+'</section><aside class="side"><div class="card"><div class="card-title"><b>Amigos</b><span>'+ms.length+'</span></div>'+ms.slice(0,6).map(m=>'<div class="member">'+av(m.nome)+'<span>'+esc(m.nome)+'</span></div>').join('')+'<button class="ghost full" data-tab="amigos">Ver todos</button></div><div class="card invite"><b>Traga seus amigos</b><p>Crie um convite individual para este ambiente.</p><button id="invite" class="primary full">Gerar convite</button></div></aside></section>'}
function profile(){return '<section class="page"><div class="profile-cover"><div class="cover-art"></div><div class="profile-main">'+av(st.me.nome,'xl')+'<div><span class="eyebrow">MEU PERFIL</span><h1>'+esc(st.me.nome)+'</h1><p>Seu perfil, sua identidade e suas escolhas.</p></div></div></div><div class="profile-grid"><div class="card"><h2>Sobre você</h2><p>Este espaço está pronto para informações, fotos e atividade.</p></div><div class="card"><h2>Minha atividade</h2><p>Recados, amizades e comunidades aparecerão aqui.</p></div></div></section>'}
function friends(){let m=st.group?.membros||[];return '<section class="page"><div class="page-head"><div><span class="eyebrow">REDE</span><h1>Amigos</h1><p>As pessoas deste ambiente.</p></div></div><div class="people-grid">'+(m.map(x=>'<article class="card person">'+av(x.nome,'large')+'<h3>'+esc(x.nome)+'</h3><small>Membro do ambiente</small></article>').join('')||'<div class="card empty">Nenhum membro ainda.</div>')+'</div></section>'}
function communities(){return '<section class="page"><div class="page-head"><div><span class="eyebrow">COMUNIDADES</span><h1>Comunidades</h1><p>Um espaço para interesses, grupos e assuntos.</p></div></div><div class="feature-grid"><article class="card feature"><b>✦</b><h2>Em destaque</h2><p>O módulo de comunidades está pronto para crescer.</p></article><article class="card feature"><b>◈</b><h2>Meus interesses</h2><p>Organize seus espaços sem transformar a rede em um sistema pesado.</p></article></div></section>'}
function settings(){return '<section class="page"><div class="page-head"><div><span class="eyebrow">PERSONALIZAÇÃO</span><h1>Monte seu SoCialBr</h1><p>Os modelos são pontos de partida. A organização pode evoluir.</p></div></div><div class="card chooser"><h2>Modelos de painel</h2><div class="choice-grid">'+models.map((x,i)=>'<button data-model="'+i+'" class="'+(st.model===i?'selected':'')+'"><span>0'+(i+1)+'</span><b>'+x+'</b><small>'+['Referência clássica','Foco no perfil','Mural em primeiro lugar','Foco em grupos','Mais conteúdo','Monte livremente'][i]+'</small></button>').join('')+'</div></div><div class="card chooser"><h2>Temas</h2><div class="theme-grid">'+themes.map((x,i)=>'<button data-theme="'+i+'" class="'+(st.theme===i?'selected':'')+'"><i style="background:'+x[3]+'"></i><i style="background:'+x[4]+'"></i><b>'+x[0]+'</b></button>').join('')+'</div></div></section>'}
async function invite(){try{let r=await api('grupos/'+st.group.grupo.id+'/convites',{});let u=location.origin+'/?convite='+r.token;await navigator.clipboard?.writeText(u);toast('Convite copiado. Válido para uma pessoa.')}catch(x){toast(x.message)}}
boot();